#
# Example .travis.yml file.
#
# Copy to your project and rename to .travis.yml.
# Customize per the instructions below.
#
language: php

php:
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

env:
  global:
    # Your site's name -- used in `drush site-install`.
    - SITE_NAME='My Drupal Site'

    # Your Pantheon site's idenfying name (i.e. as shown on the dashboard)
    - PSITE='drupalsite'

    # The Pantheon environment to push to after tests succeed.
    # DANGER: This environment will be switched from 'sftp' mode to 'git' mode
    # on every commit to github.  This will ERASE any uncommitted change made in
    # 'sftp' mode.  It is therefore advisable to avoid using 'sftp' mode on
    # the environment you select here. Create a multidev branch specifically for
    # use by Travis.
    - PENV='dev'

    # SECRET/PRIVATE VARIABLES
    #
    # These are created by using the travis command locally to encrypt some values.
    #
    # See: http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables
    #
    # PEMAIL environment variable: represents the Pantheon account e-mail with
    # access to this site. Used to authenticate to Pantheon via Terminus. You
    # must cd to your project root and run:
    #
    # travis encrypt PEMAIL='test@example.com'
    #
    - secure: MOSeFVISfZLGBiKAmZsyVjES9CLKniyAPfIRBOVhY061sxxUUo0RF6TvbfvgV4z363ejA9BPt+FXzpXmDxA1x/WD3FprSvU0e3GuZdK3Sxa927fwtCVqekZ0gEC4j4RPfZtSHd+sjqSk2gsr3PLq5gdUHcSWm9lcSlrXXIuMc5tGD23RdmiILt1KGFGd93iVhkKq7wor+GNWTwgGdiSe0uYkSSwbL2zFQlzez033mM6jZoK2UkeMj5ps38aeQDaVVN2yrCBSOdRE/bTu1MHxgra1GInCGb5Zq2rBrwtotfOZR3cqQ/cC9lo0rB+tvjmRKsWXZDiWfx5p9+ips4J0yI4cutYMdquD/n0vr+Txn5XwkWt3HHGkVFwTlrUHIv0SAqg0ll4ZSOGiS6ZCe2vYws3L2vUj5ImzRtEyJG4+NzFlJ/CHfH1BrKrdMR6ifD4EwGeJCEaeEPIU3Ii3ywdg/dACca36vQn1HjccSDRYCaF42wHRxn3pD5hf/9z8JLKxE6hvP8vOG45doGXCj2vE+5vyNpC9AaYjVy9Bw/NKQ/p0ELELMpXyeon+GPToKHK7vz0rxjiFHTQxxfch61zm2iVzTCiE8QsZG1np2EFfL/QDbC8Qjtv1g5+4ADyvxdQgNBUHKY82dgWi7UWUmJOr0ihM3A0NmAphzXQ8RLUZzOo=
    #
    # PPASS environment variable: represents the Pantheon account password for
    # the above encrypted e-mail address. Run:
    #
    # travis encrypt PPASS='my_account_password'
    #
    - secure: SfJl20e1vjJY9BdIt6m5juNC39T4vFRIpxnLo+p9o+SB3WsP/0bqj+HoQtomsXnVMqIiGABzmHzf7H2EBEgTgkJ41OJpNQEKFoZUR9aghUzZSpcd2ilGlWp0NIICTPGzkKxT9tJc3/WUVjzS8EMnaZwywq8n3szYDefl+TlFaY/V0oQ8mmjvPqrYDkieJaMz2aDceZiD3yVAra8qdfbHFfLpdy9VB3KoFT6JbcZfqU9svmzF6CRD0elLq2d9RhLrRIbPhgB07IxWk/OGMuPd1ptaN9qspXX9blHyVDyBhLwBiLTDl4DIv/wSTbe2nM8Mzp+5wR8YLGDIfCvlHPAnLddwWQfk5sJAya8SJdCr5Cec39usXt5lrHjoW5+k2NpmSGpYuWyBba0Y9/ZvT0IHwfWjB+mtySm++J5qE4EmtS5tPmvenE+uQ1mlJ8ZB8Tp7wLrBA8bAHUYvzebuW9K3iQ82Qsit2xWK7ZT7xTj8DMl+ma/LflmTTlCG4s856jPF5pVnwqYNe54XuKnxi2uzAsqrZ17buG8ZVN/Uud7wFRR/YY15/vs3t0bPWsnNeRxPJqqBHzmfZhIJJ2ELTRfaL4QqNiXGdn0y/CjZ2QmfoVEvdUtE/7EXBrj8C7G6g8QgXaVyU135w/TFhaHM2oySOUiluwNEf/+AkAs2C6TPR3A=

before_install:
  # Make sure composer is up-to-date
  - composer self-update
  # Get netstat
  - sudo apt-get update -qq
  - sudo apt-get install net-tools


install:
  - composer install

before_script:
  # Discard any emails Drupal tries to send.
  - bin/disable-php-email

script:
  # Run our behat tests on Travis
  # Install Drupal and launch the PHP built-in webserver
  - bash bin/setup-before-tests
  - bin/behat

after_success:
  # Place a passphrase-free ssh key so that you can clone and push to your
  # Pantheon git repository.
  #
  # Use the travis encrypt-file command to generate your own.
  #
  # See: http://docs.travis-ci.com/user/encrypting-files/
  #
  - openssl aes-256-cbc -K $encrypted_dbae4a756345_key -iv $encrypted_dbae4a756345_iv -in travis-ci-key.enc -out travis-ci-key -d
  - cp travis-ci-key ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  - bash bin/push-to-pantheon

after_failure:
  - if [ -f $HOME/server.log ] ; then echo "Server log:" && cat $HOME/server.log ; fi

after_script:
  - bin/stop-webserver
  - rm $HOME/server.log

notifications:
  email:
    recipients:
      # - ci-notifications@myorg.org
    on_success: always
    on_failure: always

